version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]

  dev:
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]
