version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "start"]

  dev:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]

  test:
    build:
      context: .
    environment:
      - NODE_ENV=test
    command: ["npm", "test"]
